# FROM node:16-alpine
FROM ubuntu:alpine

LABEL com.example.version="0.0.1-beta"
LABEL maintainer="STDSuperman (陌小路) <2750556766@qq.com>"

WORKDIR /code
RUN groupadd -g 1000 node \
    && useradd -u 1000 -g node -s /bin/sh node
# USER node
COPY --chown=node:node . .
# COPY . .
RUN \
  apt-get update && apt-get install expect -y --no-install-recommends \
  # && mkdir node_modules && yarn install --registry https://registry.npm.taobao.org \
  && chmod -R +x ./bash \
  && expect ./bash/expect.ex \
  # && . $HOME/.cargo/env \
  && mkdir mcl \
  && cd mcl \
  && git clone https://github.com/iTXTech/mcl-installer.git \
  && cd mcl-installer \
  && cargo build --features native-tls --release \
  && cd target/release \
  && cd ../../ \
  && strip mcl-installer \
  && apt-get purge --auto-remove \
  && rm -rf /tmp/* /var/lib/apt/lists/* \
  # && apk del .build-deps-yarn
USER node
CMD ["/bin/bash"]

LABEL \
  org.label-schema.build-date="$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
  org.label-schema.version="$DOCKER_TAG" \
  org.label-schema.name="QQRobot" \