services:
  app:
    depends_on:
      - mysql
      - redis
    ports:
      - "9999:9999"
    build: .
    volumes:
      - .:/code

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  mysql:
    image: "mysql:5.7"
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 110120
      MYSQL_DATABASE: "QQROBOT"